### PR TITLE
Refactor of TAD project name to AMT

### PR DESCRIPTION
**Pull request by laurensWe**
# Description

- Refactor any reference of TAD to AMT because of change of project name
- Rename the sonar project to ai-validation-infra instead of tad-validation-infra

Resolves #

## Checklist

Please check all the boxes that apply to this pull request using "x":

- [x]  I have tested the changes locally and verified that they work as expected.
- [x]  I have followed the project's coding conventions and style guidelines.
- [x]  I have rebased my branch onto the latest commit of the main branch.
- [x]  I have squashed or reorganized my commits into logical units.
- [x]  I have read, understood and agree to the [Developer Certificate of Origin](../blob/main/DCO.md), which this project utilizes.

### CODE REVIEW

**Comment by laurensWe** [comment]
!Blocked because the namespaces of Digilab should change first also

**Review by berrydenhartog — APPROVED** [review]
LGTM

**Review by berrydenhartog — DISMISSED** [review]
LGTM

**Review by berrydenhartog — APPROVED** [review]
LGTM

**Pull request merged**
